In [37]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import wandb

sns.set_style('darkgrid')
ROOT = os.getcwd()
print(ROOT)

/mnt/jfs_hpc/seaweed1/uperdfi/home/gahizon/SAR_flood_segmentation/src/notebooks

In [38]:
PATH = os.path.join(ROOT, 'results.csv')
df = pd.read_csv(PATH)
df.sample()

,Name,Created,label_type,model,backbone,test_miou,holdout_miou,trainable_params,expand,lr,scheduler,transforms,alpha,T,teacher
130,pleasant-pond-524,2024-12-17T13:49:35.000Z,WeaklyLabeled,u-net++,resnet152,73.98996,55.09404,83621521,1,0.00005,CosineAnnealingWarmRestarts,"[""shiftscalerotate"",""flip"",""distort""]",NaN,NaN,NaN

In [39]:
trainable_params = df.groupby(['model', 'backbone'], as_index=False)['trainable_params'].max()
trainable_params.sort_values('trainable_params')

      model                            backbone  trainable_params
2   linknet  timm-mobilenetv3_small_minimal_100            856491
1   linknet          timm-mobilenetv3_small_100           1354611
0   linknet  timm-mobilenetv3_large_minimal_100           2614313
8     u-net  timm-mobilenetv3_small_minimal_100           3087529
7     u-net          timm-mobilenetv3_small_100           3585649
6     u-net  timm-mobilenetv3_large_minimal_100           5127081
4     u-net                            resnet18          14328209
10  u-net++                            resnet18          15970449
5     u-net                            resnet50          32521105
11  u-net++                            resnet50          48985745
3     u-net                           resnet152          67156881
9   u-net++                           resnet152          83621521

In [40]:
# For each unique (model, backbone), get the max test_miou
hand_labeled_test = df.loc[(df['teacher'].isna()) & (df['label_type']=='HandLabeled')
    ,:].groupby(['model', 'backbone'], as_index=False)['test_miou'].max()
hand_labeled_test=hand_labeled_test.merge(trainable_params, on=['model', 'backbone'], how='left')
hand_labeled_test.sort_values('test_miou', ascending=False)

      model                            backbone  test_miou  trainable_params
11  u-net++                            resnet50  75.068649          48985745
5     u-net                            resnet50  74.075043          32521105
3     u-net                           resnet152  74.020424          67156881
10  u-net++                            resnet18  73.916023          15970449
9   u-net++                           resnet152  73.699120          83621521
8     u-net  timm-mobilenetv3_small_minimal_100  73.588600           3087529
4     u-net                            resnet18  73.421875          14328209
6     u-net  timm-mobilenetv3_large_minimal_100  71.864410           5127081
2   linknet  timm-mobilenetv3_small_minimal_100  71.824173            856491
7     u-net          timm-mobilenetv3_small_100  71.434059           3585649
0   linknet  timm-mobilenetv3_large_minimal_100  71.262955           2614313
1   linknet          timm-mobilenetv3_small_100  70.639587           1354611

In [41]:
# For each unique (model, backbone), get the max test_miou
hand_labeled_holdout = df.loc[(df['teacher'].isna()) & (df['label_type']=='HandLabeled')
    ,:].groupby(['model', 'backbone'], as_index=False)['holdout_miou'].max()
hand_labeled_holdout=hand_labeled_holdout.merge(trainable_params, on=['model', 'backbone'], how='left')
hand_labeled_holdout.sort_values('holdout_miou', ascending=False)

,model,backbone,holdout_miou,trainable_params
9,u-net++,resnet152,62.095650,83621521
11,u-net++,resnet50,59.665974,48985745
7,u-net,timm-mobilenetv3_small_100,58.380581,3585649
3,u-net,resnet152,57.496811,67156881
1,linknet,timm-mobilenetv3_small_100,56.603367,1354611
10,u-net++,resnet18,54.235977,15970449
0,linknet,timm-mobilenetv3_large_minimal_100,53.776508,2614313
6,u-net,timm-mobilenetv3_large_minimal_100,52.961765,5127081
5,u-net,resnet50,51.601822,32521105
2,linknet,timm-mobilenetv3_small_minimal_100,50.781303,856491
4,u-net,resnet18,50.222492,14328209
8,u-net,timm-mobilenetv3_small_minimal_100,41.970165,3087529

In [42]:
# For each unique (model, backbone), get the max test_miou
weakly_labeled_test = df.loc[(df['teacher'].isna()) & (df['label_type']=='WeaklyLabeled')
    ,:].groupby(['model', 'backbone'], as_index=False)['test_miou'].max()
weakly_labeled_test=weakly_labeled_test.merge(trainable_params, on=['model', 'backbone'], how='left')
weakly_labeled_test.sort_values('test_miou', ascending=False)

      model                            backbone  test_miou  trainable_params
10  u-net++                            resnet50  74.811890          48985745
8   u-net++                           resnet152  74.461533          83621521
4     u-net                            resnet18  74.289345          14328209
9   u-net++                            resnet18  74.061180          15970449
3     u-net                           resnet152  73.994713          67156881
7     u-net          timm-mobilenetv3_small_100  73.851952           3585649
5     u-net                            resnet50  73.378601          32521105
6     u-net  timm-mobilenetv3_large_minimal_100  73.296867           5127081
2   linknet  timm-mobilenetv3_small_minimal_100  73.232567            856491
0   linknet  timm-mobilenetv3_large_minimal_100  72.738533           2614313
1   linknet          timm-mobilenetv3_small_100  71.800575           1354611

In [43]:
# For each unique (model, backbone), get the max test_miou
weakly_labeled_holdout = df.loc[(df['teacher'].isna()) & (df['label_type']=='WeaklyLabeled')
    ,:].groupby(['model', 'backbone'], as_index=False)['holdout_miou'].max()
weakly_labeled_holdout=weakly_labeled_holdout.merge(trainable_params, on=['model', 'backbone'], how='left')
weakly_labeled_holdout.sort_values('holdout_miou', ascending=False)

,model,backbone,holdout_miou,trainable_params
10,u-net++,resnet50,61.030449,48985745
7,u-net,timm-mobilenetv3_small_100,60.144489,3585649
8,u-net++,resnet152,59.049206,83621521
3,u-net,resnet152,57.549847,67156881
2,linknet,timm-mobilenetv3_small_minimal_100,56.267368,856491
1,linknet,timm-mobilenetv3_small_100,55.528458,1354611
6,u-net,timm-mobilenetv3_large_minimal_100,54.752708,5127081
0,linknet,timm-mobilenetv3_large_minimal_100,54.124386,2614313
4,u-net,resnet18,50.870354,14328209
9,u-net++,resnet18,49.251644,15970449
5,u-net,resnet50,39.978382,32521105